<a href="https://colab.research.google.com/github/dineshkumarsarangapani/Machine_learning_IITM/blob/main/solutions/(5)_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Arrays

We will study `NumPy` arrays in more detail. 

In [1]:
import numpy as np

## Arrays

It should have become amply clear by now that both vectors and matrices are `NumPy` arrays. Each array in `NumPy` has a dimension. Vectors are one-dimensional arrays while matrices are two-dimensional arrays. For example:

$$
\mathbf{x} = \begin{bmatrix}
1\\
2\\
3
\end{bmatrix}, 
\mathbf{M} = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6
\end{bmatrix}
$$

In `NumPy`:

In [3]:
x = np.array([[1],[2],[3]])
x

array([[1],
       [2],
       [3]])

In [5]:
m = np.array([[1,2], [3,4], [5,6]])
m

array([[1, 2],
       [3, 4],
       [5, 6]])

## Three dimensional array

Though we will mostly restrict ourselves to arrays of dimension one and two, nothing stops us from working with higher dimensional arrays. For example, consider a 3-dimensional array. This could be visualized as a list of matrices:

$$
\begin{bmatrix}
\begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}\\ 
\begin{bmatrix}
7 & 8 & 9\\
10 & 11 & 12
\end{bmatrix}\\
\end{bmatrix}
$$

This would be a $2 \times 2 \times 3$ array. In `NumPy`:

In [8]:
y = np.array([[[1,2,3],[4,5,6]],[[7,8,9], [10,11,12]]])
y

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
y.shape

(2, 2, 3)

## Reshaping

Arrays can be reshaped. We will do a number of examples here.

### Example-1: Vector to matrix

We start with a vector:

$$
\mathbf{x} = \begin{bmatrix}
1 & 2 & 3 & 4 & 5 & 6
\end{bmatrix}
$$

We can reshape it into the following matrix:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6
\end{bmatrix}
$$

In `NumPy`:

In [10]:
x = np.array([1,2,3,4,5,6])
x.shape

(6,)

In [12]:
x.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
x.reshape(3,2, order='F') # F stands for fortorn

array([[1, 4],
       [2, 5],
       [3, 6]])

In [13]:
x.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# Cannot do this ? why?
x.reshape(2,2) 

ValueError: ignored

In [16]:
# Cannot do this ? why?
x.reshape(6,1) 

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [17]:
x.reshape(1,6) 

array([[1, 2, 3, 4, 5, 6]])

### Example-2: Matrix to vector

We now start with a matrix:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}
$$

We can now reshape it into a vector:

$$
\mathbf{x} = \begin{bmatrix}
1 & 2 & 3 & 4 & 5 & 6
\end{bmatrix}
$$

In `NumPy`:

In [18]:
m = np.array([[1,2,3], [4,5,6]])
m.shape

(2, 3)

In [22]:
m.reshape(6,)

array([1, 2, 3, 4, 5, 6])

### Example-3: Matrix to matrix

We can reshape a matrix into another matrix as well. Sometimes, we may not want to specify the dimensions completely. In such cases, we can let `NumPy` figure them out by letting one of the dimensions to be $-1$. For example:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}
$$

Let us say we want to reshape it in such a way that there are three rows:

$$
\mathbf{P} = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6
\end{bmatrix}
$$

In `NumPy`:

In [23]:
m = np.array([[1,2,3], [4,5,6]])
m.reshape(3, -1) # -1 is unknwon dimention

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
m.reshape(3, -1, order='F') # -1 is unknwon dimention

array([[1, 5],
       [4, 3],
       [2, 6]])

## Matrix-vector addition

Sometimes we would have to add a vector to each row or column of a matrix. There are two cases to consider. If the vector to be added is a:

- row vector
- column vector


### Row-vector

Consider the following matrix $\mathbf{M}$ and vector $\mathbf{b}$:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}, \mathbf{b} = \begin{bmatrix}
1 & 2 & 3
\end{bmatrix}
$$

There is a slight abuse of notation as we can't add a matrix and a vector together. However, the context often makes this clear:

$$
\mathbf{M} + \mathbf{b} = \begin{bmatrix}
2 & 4 & 6\\
5 & 7 & 9
\end{bmatrix}
$$

In `NumPy`:

In [25]:
m = np.array([[1,2,3], [4,5,6]])
b = np.array([1,2,3])
m+b

array([[2, 4, 6],
       [5, 7, 9]])

### Column-vector

Now, consider another pair:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}, \mathbf{b} = \begin{bmatrix}
1\\
2
\end{bmatrix}
$$

In this case, we have:

$$
\mathbf{M} + \mathbf{b} = \begin{bmatrix}
2 & 3 & 4\\
6 & 7 & 8
\end{bmatrix}
$$

In `NumPy`:

In [35]:
m = np.array([[1,2,3], [4,5,6]])
b = np.array([1,2])
print(b)
print(b.shape)
b = b.reshape(2,1)
print(b)
print(b.shape)
m+b

[1 2]
(2,)
[[1]
 [2]]
(2, 1)


array([[2, 3, 4],
       [6, 7, 8]])

## Indexing and Slicing an array

Just like lists in Python, `NumPy` arrays can be indexed and sliced. Slicing is useful if we want to work with a portion of an array. We will look at some examples.

### Example-1: Row-slice

We will extract the third row of the matrix $\mathbf{M}$:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6\\
7 & 8\\
9 & 10
\end{bmatrix}
$$



In `NumPy`:

In [37]:
M = np.array([[1,2],[3,4], [5,6], [7,8], [9,10]])
M[2]

array([5, 6])

### Example-2: Column slice

Let us now extract the second column of the following matrix:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}
$$

In `NumPy`:

In [44]:
M = np.array([[1,2, 3],[4, 5, 6], [7,8, 9]])
M[:,1]


array([2, 5, 8])

In [46]:
M[1,:]


array([4, 5, 6])

### Example-3: Submatrix slice

Now, we want to extract the $2 \times 2$ submatrix colored in blue from $M$:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & \color{blue}7 & \color{blue}8\\
9 & 10 & \color{blue}{11} & \color{blue}{12}\\
13 & 14 & 15 & 16
\end{bmatrix}
$$

In `NumPy`:

In [51]:
# M = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
N = np.array(np.linspace(1,16, 16))
M = N.reshape(4,-1)
M[1:3, 2:4]

array([[ 7.,  8.],
       [11., 12.]])

### Example-4: Indexing using arrays

`NumPy` arrays themselves can be used as indices to retreive different parts of the array. For example:

$$
\mathbf{x} = \begin{bmatrix}
0 & 1 & 2 & 3 & 4 & 5 & 6
\end{bmatrix}
$$

Let us say that we are interested in retreiving indices: `[1, 3, 6]`. 

In `NumPy`:

In [56]:
x = np.array([0,1,2,3,4,5,6])
x[[1,3,6]]

array([1, 3, 6])

### Example-5: Filtering particular values

Sometimes we are interested in those elements of the array that possess a particular property:

$$
\mathbf{x} = \begin{bmatrix}
3 & 1 & 0 & -4 & -2 & 1 & 5
\end{bmatrix}
$$

Let us try to extract all elements that are positive.

In `NumPy`:

In [58]:
x = np.array([3,1,0,-4,-2,1,5])
x[x > 0]

array([3, 1, 1, 5])

## Operations along axes

Sometimes we may wish to do some operations on all the row-vectors of a matrix or all the column-vectors of the matrix. The idea of `axis` is important to understand how these operations can be done.

### Top-bottom

Top-bottom operations are done on row-vectors. For example, consider the matrix:

$$
\mathbf{A} = \begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8
\end{bmatrix}
$$

The sum of the row-vectors of the matrix is a vector:

$$
\text{rsum}(\mathbf{A}) = \begin{bmatrix}
6 & 8 & 10 & 12
\end{bmatrix}
$$

In `NumPy`:

In [63]:
x = np.linspace(1, 8, 8)
x = x.reshape(2,-1)
print(x)
x.sum(axis=0)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


array([ 6.,  8., 10., 12.])

In [64]:
x.sum(axis=1)

array([10., 26.])

### Left-right

Left-right operations are done on column-vectors.

$$
\mathbf{A} = \begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8
\end{bmatrix}
$$

The sum of the column-vectors of the matrix is a vector:

$$
\text{csum}(\mathbf{A}) = \begin{bmatrix}
10\\
26
\end{bmatrix}
$$

In `NumPy`:

In [65]:
x.sum(axis=1)

array([10., 26.])

### Sum, Mean, Variance, Norm

Some of the operations that can be done in this manner. Let us use the following matrix to demonstrate this:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}
$$

Let us find the following quantities:

- sum of column-vectors
- mean of row-vectors
- variance of column-vectors

In [71]:
x = np.linspace(1, 9, 9)
x = x.reshape(3,-1)
x.sum(axis=0) # sum of col-vector

array([12., 15., 18.])

In [72]:
x.mean(axis=1) # mean of row-vector

array([2., 5., 8.])

In [73]:
x.var(axis=0) # var of col-vector

array([6., 6., 6.])

## Stacking arrays

Sometimes, we would want to stack arrays. Consider the two matrices:

$$
\mathbf{A} =
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix},
\mathbf{B} =
\begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}
$$

There are two ways to stack these two matrices:

- top-bottom
- left-right

### Top-bottom

We could stack the two matrices along the rows, $\mathbf{A}$ on top of $\mathbf{B}$:

$$
\mathbf{C} =
\begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6\\
7 & 8
\end{bmatrix}
$$

In `NumPy`:

In [77]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
C = np.concatenate((A, B), axis=0)
C

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [78]:
C = np.concatenate((A, B), axis=1)
C

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Left-right

We could stack the two matrices along the columns, $\mathbf{A}$ to the left of $\mathbf{B}$:

$$
\mathbf{C} =
\begin{bmatrix}
1 & 2 & 5 & 6\\
3 & 4 & 7 & 8\\
\end{bmatrix}
$$

In `NumPy`:

In [79]:
C = np.concatenate((A, B), axis=1)
C

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])