<a href="https://colab.research.google.com/github/dineshkumarsarangapani/Machine_learning_IITM/blob/main/MLP/Mock_OPPE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [125]:
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()

In [126]:
data.data.shape

(569, 30)

In [127]:
len(data.feature_names)

30

In [128]:
data.target == 0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False, False, False, False,  True,
        True, False,  True,  True, False, False, False, False,  True,
       False,  True,  True, False, False, False, False,  True, False,
        True,  True, False,  True, False,  True,  True, False, False,
       False,  True,  True, False,  True,  True,  True, False, False,
       False,  True, False, False,  True,  True, False, False, False,
        True,  True, False, False, False, False,  True, False, False,
        True, False, False, False, False, False, False, False, False,
        True,  True,  True, False,  True,  True, False, False, False,
        True,  True,

In [129]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [130]:
type(data.data[:,1])

numpy.ndarray

In [131]:
from sklearn.feature_selection import r_regression

r_regression(data.data[:,0].reshape(-1,1), data.data[:,2].reshape(-1,1))

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0.99785528])

In [132]:
from sklearn.impute import SimpleImputer
import numpy as np
miss = [[7, 16, 31], [np.nan, np.nan, 66], [12, 5, np.nan],[98, np.nan, 92]]

In [133]:
imputer = SimpleImputer()
imputer.fit_transform(miss)

array([[ 7. , 16. , 31. ],
       [39. , 10.5, 66. ],
       [12. ,  5. , 63. ],
       [98. , 10.5, 92. ]])

In [134]:
from sklearn.preprocessing import FunctionTransformer

trans = FunctionTransformer(np.log10)

In [135]:
trans.transform([[1, 1], [2, 3],[10,100]] )

array([[0.        , 0.        ],
       [0.30103   , 0.47712125],
       [1.        , 2.        ]])

In [136]:
np.log10?

In [137]:
import pandas as pd
data_iris = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', names=['sepal length', 'sepal width', 'petal length', 'petal width','label'])

In [138]:
data_iris.head()

sepal length  sepal width  petal length  petal width        label
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [139]:
from sklearn.preprocessing import PolynomialFeatures
poly_feat = PolynomialFeatures()
data_iris_poly = poly_feat.fit_transform(data_iris[['sepal length', 'sepal width', 'petal length', 'petal width']])

In [140]:
data_iris.shape

(150, 5)

In [141]:
data_iris_poly.shape

(150, 15)

In [142]:
from sklearn.datasets import fetch_california_housing

X_data_house, y_data_rate = fetch_california_housing(return_X_y=True)

In [143]:
from sklearn.feature_selection import SelectPercentile,mutual_info_regression

In [144]:
# SelectPercentile?

In [145]:
X_new = SelectPercentile(mutual_info_regression, percentile=10).fit_transform(X_data_house, y_data_rate)
X_new.shape

(20640, 1)

In [146]:
X_data_house.shape

(20640, 8)

In [147]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_data_house, y_data_rate, test_size=0.2, random_state=42)

In [148]:
X_train.shape

(16512, 8)

In [149]:
X_test.shape

(4128, 8)

In [150]:
from sklearn.dummy import DummyRegressor

In [151]:
reg_d = DummyRegressor(strategy='mean')

In [152]:
reg_d.fit(X_train, y_train)

DummyRegressor()

In [153]:
y_pred = reg_d.predict(X_test)

In [154]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

-0.00021908714592466794

In [155]:
from sklearn.preprocessing import MinMaxScaler

In [156]:
scale = MinMaxScaler()
X_train = scale.fit_transform(X_train)

In [157]:
X_test = scale.transform(X_test)

In [158]:
from sklearn.linear_model import SGDRegressor, LinearRegression

In [159]:
sgd = SGDRegressor()

In [160]:
sgd.fit(X_train, y_train)

SGDRegressor()

In [161]:
y_pred = sgd.predict(X_test)

In [162]:
from sklearn.metrics import mean_absolute_error

In [163]:
mean_absolute_error(y_test, y_pred)

0.5580130611232614

In [164]:
y_pred_train = sgd.predict(X_train)

In [165]:
mean_absolute_error(y_train, y_pred_train)

0.556152427394173

In [166]:
from sklearn.model_selection import cross_validate

In [167]:
linreg  = LinearRegression()
cross_validate?

In [168]:
cross_validate(linreg, X_data_house, y_data_rate, cv=5)

{'fit_time': array([0.02223516, 0.01557851, 0.01234937, 0.01418734, 0.01242566]),
 'score_time': array([0.00095677, 0.00204611, 0.00156474, 0.00214052, 0.00142956]),
 'test_score': array([0.54866323, 0.46820691, 0.55078434, 0.53698703, 0.66051406])}

In [169]:
from sklearn.datasets import load_diabetes

data_dia = load_diabetes()

In [170]:
data_dia.data.shape

(442, 10)

In [185]:
data_dia.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [171]:
from sklearn.preprocessing import StandardScaler
scale_stg = StandardScaler()

In [172]:
X_dia = scale_stg.fit_transform(data_dia.data)

In [173]:
X_train_dia, X_test_dia, y_train_dia, y_test_dia = train_test_split(X_dia, data_dia.target, test_size=0.2, random_state=10)

In [174]:
lindia = LinearRegression()

In [175]:
lindia.fit(X_train_dia, y_train_dia)

LinearRegression()

In [176]:
y_pred_dia = lindia.predict(X_test_dia)

In [177]:
r2_score(y_test_dia,y_pred_dia)

0.5341988244945843

In [178]:
lindia.intercept_

152.25553849048583

In [179]:
lindia.coef_

array([ -0.18490165, -10.73190006,  24.63419925,  15.61612821,
       -34.58951403,  19.54679579,   3.81732698,  10.37783679,
        33.49852404,   1.90371458])

In [218]:
from sklearn.linear_model import RidgeCV
rr = RidgeCV(alphas=np.logspace(-4,0,num=20))

In [222]:
cross_validate(rr, X_train_dia, y_train_dia, cv=5,  scoring='neg_mean_absolute_error')

{'fit_time': array([0.00933933, 0.00417614, 0.00304055, 0.00325441, 0.00315356]),
 'score_time': array([0.00069594, 0.0005877 , 0.00039196, 0.00048637, 0.00054979]),
 'test_score': array([-52.72284138, -44.56228134, -41.17144351, -45.37837184,
        -42.07195033])}

In [223]:
np.array([-52.72284138, -44.56228134, -41.17144351, -45.37837184,
        -42.07195033]).mean()

-45.181377680000004

0.130148868759