<a href="https://colab.research.google.com/github/dineshkumarsarangapani/Machine_learning_IITM/blob/main/MLP/week7_mlp_graded_Part_B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris
data = load_iris()

In [ ]:
from sklearn.model_selection import GridSearchCV


kernels = ['linear' , 'rbf']

Regularization = [1,15,25]

gamma = 'auto'

Cross Validation = 4

random_state=0

In [ ]:
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV
iris = datasets.load_iris()
parameters = {'kernel':('linear', 'rbf'), 'C':[1, 15, 25], 'gamma':['auto']}
svc = svm.SVC()
clf = GridSearchCV(svc, parameters,cv=4)
clf.fit(iris.data, iris.target)

GridSearchCV(cv=4, estimator=SVC(),
             param_grid={'C': [1, 15, 25], 'gamma': ['auto'],
                         'kernel': ('linear', 'rbf')})

In [ ]:
sorted(clf.cv_results_.keys())

['mean_fit_time',
 'mean_score_time',
 'mean_test_score',
 'param_C',
 'param_gamma',
 'param_kernel',
 'params',
 'rank_test_score',
 'split0_test_score',
 'split1_test_score',
 'split2_test_score',
 'split3_test_score',
 'std_fit_time',
 'std_score_time',
 'std_test_score']

In [ ]:
clf.best_score_

0.9799075391180654

In [ ]:
clf.best_estimator_

SVC(C=1, gamma='auto', kernel='linear')

# Part 2

In [ ]:
url = 'https://raw.githubusercontent.com/dineshkumarsarangapani/Machine_learning_IITM/main/MLP/Social_Network_Ads.csv'

In [ ]:
import pandas as pd
data = pd.read_csv(url)
data.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

scale = StandardScaler()
X = data[['Age','EstimatedSalary']]
y = data['Purchased']
print(X)

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]


In [ ]:
# X = scale.fit_transform(X)
# X_test = scale.transform(X_test)

In [ ]:
# X[5]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.75, shuffle=True, random_state = 0)
X_test.shape

(100, 2)

In [ ]:
# scale.fit(X)
X_train = scale.fit_transform(X_train)
X_test = scale.transform(X_test)

In [ ]:
from sklearn.svm import LinearSVC,SVC
# svc = SVC(random_state = 0, kernel='linear')
svc = LinearSVC(random_state = 0)

In [ ]:
svc.fit(X_train, y_train)

LinearSVC(random_state=0)

In [ ]:
y_pred = svc.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix

accuracy_score(y_test, y_pred)

0.9

In [ ]:
svc.score(X_test, y_test)

0.9

In [ ]:
confusion_matrix(y_test, y_pred)

array([[66,  2],
       [ 8, 24]])

# Part 3

In [ ]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784')

/usr/local/lib/python3.9/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [ ]:

x = mnist.data
y = mnist.target

In [ ]:
type(x)

pandas.core.frame.DataFrame

In [ ]:
x_train = x[0:20000]
x_test = x[20000:25000]
print(x_train.shape)
print(x_test.shape)

(20000, 784)
(5000, 784)


In [ ]:
y_train = y[:20000]
y_test = y[20000:25000]
print(y_train.shape)
print(y_test.shape)

(20000,)
(5000,)


In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler,StandardScaler

ImportError: ignored

In [ ]:
pipe= Pipeline([("MinMaxScaler", MinMaxScaler()), ("SVC", SVC(kernel='linear', decision_function_shape='ovr', class_weight=None, random_state=0))])

In [ ]:
pipe.fit(x_train, y_train)

Pipeline(steps=[('MinMaxScaler', MinMaxScaler()),
                ('SVC', SVC(kernel='linear', random_state=0))])

In [ ]:
pipe.score(x_test, y_test)

0.9246

In [ ]:
y_pred = pipe.predict(x_test)

In [ ]:
from sklearn.metrics import multilabel_confusion_matrix
mat = confusion_matrix(y_test, y_pred)
mat

array([[469,   0,   1,   0,   0,   5,   1,   1,   1,   0],
       [  1, 555,   2,   4,   0,   1,   1,   1,   3,   0],
       [  5,   4, 479,   6,   9,   1,   3,   6,   7,   1],
       [  3,   3,  13, 462,   0,  19,   0,   3,   9,   4],
       [  2,   0,   6,   0, 468,   1,   2,   4,   1,  16],
       [ 14,   0,   0,  18,   2, 405,   3,   2,   7,   9],
       [  1,   2,   2,   0,   6,   9, 471,   0,   0,   0],
       [  0,   2,   4,   1,   7,   1,   0, 483,   0,   6],
       [  3,  10,  11,  15,   0,  19,   6,   3, 396,   3],
       [  3,   6,   1,   2,  21,   0,   0,  26,   2, 435]])

In [ ]:
import numpy as np
np.diagonal(mat).sum()

4623

In [ ]:
from sklearn.metrics import f1_score, recall_score, precision_score

In [ ]:
y_test.ravel()

['5', '9', '7', '3', '7', ..., '5', '1', '2', '9', '9']
Length: 5000
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']

In [ ]:
x_test

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
20000     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
20001     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
20002     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
20003     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
20004     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
24995     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
24996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
24997     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
24998     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
24999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
20000      0.0  ...       0.0       0.0       0.0       0.0       0.0   
20001      0.0  ...       0.0       0.0       0.0       0.0       0.0   
20002      0.0  ...       0.0       0.0       0.0       0.0       0.0   
20003      0.0  ...       0.0       0.0       0.0       0.0       0.0   
20004      0.0  ...       0.0       0.0       0.0       0.0       0.0   
...        ...  ...       ...       ...       ...       ...       ...   
24995      0.0  ...       0.0       0.0       0.0       0.0       0.0   
24996      0.0  ...       0.0       0.0       0.0       0.0       0.0   
24997      0.0  ...       0.0       0.0       0.0       0.0       0.0   
24998      0.0  ...       0.0       0.0       0.0       0.0       0.0   
24999      0.0  ...       0.0       0.0       0.0       0.0       0.0   

       pixel780  pixel781  pixel782  pixel783  pixel784  
20000       0.0       0.0       0.0       0.0       0.0  
20001       0.0       0.0       0.0       0.0       0.0  
20002       0.0       0.0       0.0       0.0       0.0  
20003       0.0       0.0       0.0       0.0       0.0  
20004       0.0       0.0       0.0       0.0       0.0  
...         ...       ...       ...       ...       ...  
24995       0.0       0.0       0.0       0.0       0.0  
24996       0.0       0.0       0.0       0.0       0.0  
24997       0.0       0.0       0.0       0.0       0.0  
24998       0.0       0.0       0.0       0.0       0.0  
24999       0.0       0.0       0.0       0.0       0.0  

[5000 rows x 784 columns]

In [ ]:
f1_score(y_test, y_pred,average='weighted')

0.9242341822537996

In [ ]:
recall_score(y_test, y_pred,average='weighted')

0.9246

In [ ]:
precision_score(y_test, y_pred,average='weighted')

0.9245834577056025

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, train_size=0.5, random_state = 42)

In [ ]:
pipe= Pipeline([("StandardScalar", StandardScaler()), ("SVC", SVC(kernel='poly',degree=3, decision_function_shape='ovr', class_weight='balanced', C=10, random_state=42))])

In [ ]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('StandardScalar', StandardScaler()),
                ('SVC',
                 SVC(C=10, class_weight='balanced', kernel='poly',
                     random_state=42))])

In [ ]:
y_pred = pipe.predict(X_test)

In [ ]:
y_pred = pipe.predict(X_test)

In [ ]:
f1_score(y_test, y_pred, average='weighted')

0.9723258740744225

In [ ]:
data = load_iris()


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, train_size=0.7, random_state = 42)

In [ ]:
model= SVC(kernel='poly',gamma='auto', C=10, random_state=42)

In [ ]:
model.fit(X_train, y_train)

SVC(C=10, gamma='auto', kernel='poly', random_state=42)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
accuracy_score(y_test, y_pred)

1.0

In [ ]:
model2= SVC(kernel='sigmoid',gamma='auto', C=25, random_state=42)

In [ ]:
model2.fit(X_train, y_train)

SVC(C=25, gamma='auto', kernel='sigmoid', random_state=42)

In [ ]:
y_pred = model2.predict(X_test)

In [ ]:
accuracy_score(y_test, y_pred)

0.28888888888888886

In [ ]:
x=data.data
y=data.target

In [ ]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [ ]:
i = y[y==0]
len(i)

50

In [ ]:
y = y[y!=0]
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
x = x[50:150]
x.shape

(100, 4)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, train_size=0.75, random_state = 0)

In [ ]:
pipe= Pipeline([("MinMaxScaler", MinMaxScaler()), ("SVC", SVC())])

In [ ]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('MinMaxScaler', MinMaxScaler()), ('SVC', SVC())])

In [ ]:
y_pred = pipe.predict(X_test)

In [ ]:
precision_score(y_test, y_pred)

1.0